### ISSUE TITLE
Create Kubestronaut landing page

### ISSUE THREAD

**Issue by caniszczyk** [cncf/kubestronaut#3]
We should reuse https://www.cncf.io/people/ambassadors/ and create https://www.cncf.io/people/kubestronauts

**Comment by guillermotti** [comment]
Is there any guide on how to create a landing page? If so, I would love to get involved and help to create it if possible :)

**Comment by caniszczyk** [comment]
@guillermotti we'd love your help but we have an internal person who can spin this up quickly!

**Comment by cjyabraham** [comment]
@huats can you let me know when you have all the data on the initial set of people ready?

**Comment by PeterBarczi** [comment]
> @guillermotti we'd love your help but we have an internal person who can spin this up quickly!

Is there any update?

**Comment by cjyabraham** [comment]
This is updated here: https://www.cncf.io/training/kubestronaut/
